name: Devtools package test
on: [push]
jobs:
  Devtools package test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("devtools")'
      - name: Perform test
        run: Rscript -e 'devtools::check()'

