name: Docker image build
on: [push]
jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . --file Dockerfile --tag mediwatch:$(date +%s)
